import {Inter} from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({subsets: ['latin']})

export const metadata = {
	title: 'e-comerce',
	description: 'Generated by create next app',
}

export default function RootLayout({children}) {
	return (
		<html lang='es'>
			<body  suppressHydrationWarning={true}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
